import {
  drawDocumentHeader,
  drawFooter,
  drawKeyValueBlock,
  drawLineItemTable,
  drawTotals,
  formatBps,
  formatDate,
  formatPaise,
  formatQuantity,
} from "../layout.js";
import { createDocument, renderToBuffer } from "../render.js";

export interface PurchaseOrderPdfInput {
  organizationName: string;
  poNumber: string;
  status: string;
  currency: string;
  taxRateBps: number;
  subtotalPaise: number;
  taxPaise: number;
  totalPaise: number;
  expectedDeliveryDate: Date | null;
  approvedAt: Date | null;
  approvedBy: string | null;
  createdAt: Date;
  supplier: { name: string; email: string | null; phone: string | null };
  items: {
    description: string;
    quantity: number;
    unitPricePaise: number;
    lineTotalPaise: number;
  }[];
}

export async function renderPurchaseOrderPdf(input: PurchaseOrderPdfInput): Promise<Buffer> {
  const doc = createDocument();
  const promise = renderToBuffer(doc);

  drawDocumentHeader(doc, {
    organizationName: input.organizationName,
    title: "Purchase Order",
    documentNumber: input.poNumber,
    date: input.createdAt,
  });

  drawKeyValueBlock(doc, "Supplier", [
    ["Name", input.supplier.name],
    ["Email", input.supplier.email ?? "—"],
    ["Phone", input.supplier.phone ?? "—"],
  ]);

  drawKeyValueBlock(doc, "Order details", [
    ["Status", input.status],
    ["Expected delivery", formatDate(input.expectedDeliveryDate)],
    ...(input.approvedAt
      ? ([["Approved at", formatDate(input.approvedAt)]] as [string, string][])
      : []),
    ...(input.approvedBy ? ([["Approved by", input.approvedBy]] as [string, string][]) : []),
  ]);

  drawLineItemTable(
    doc,
    [
      { label: "Description", width: 220 },
      { label: "Qty", width: 60, align: "right" },
      { label: "Unit price", width: 110, align: "right" },
      { label: "Line total", width: 110, align: "right" },
    ],
    input.items.map((item) => [
      item.description,
      formatQuantity(item.quantity),
      formatPaise(item.unitPricePaise, input.currency),
      formatPaise(item.lineTotalPaise, input.currency),
    ]),
  );

  drawTotals(doc, [
    ["Subtotal", formatPaise(input.subtotalPaise, input.currency)],
    [`Tax (${formatBps(input.taxRateBps)})`, formatPaise(input.taxPaise, input.currency)],
    ["Total", formatPaise(input.totalPaise, input.currency)],
  ]);

  drawFooter(
    doc,
    "This purchase order was generated by a hackathon procurement simulator and is not a legally binding document.",
  );

  doc.end();
  return promise;
}
